{
 "title": "Kubernetes Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "RG",
    "label": "Resource group",
    "query": {
     "query": "label_values(kubernetes_pod_container_state_code,resource_group)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod phase summary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count by (phase, phase_reason) (group by (pod_name, phase, phase_reason) (kubernetes_pod_container_state_code{resource_group=\"$RG\"}))",
     "legendFormat": "Pod status: {{phase}} {{phase_reason}}"
    }
   ]
  },
  {
   "title": "Pod readiness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(count by (pod_name) (kubernetes_pod_container_state_code{resource_group=\"$RG\", readiness=\"ready\"})) == bool (count by (pod_name) (kubernetes_pod_container_state_code{resource_group=\"$RG\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods per host",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "count by (node_name) (group by (node_name, pod_name) (kubernetes_pod_container_state_code{}))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Containers per host",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "count by (node_name) (kubernetes_pod_container_state_code{})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Other cluster resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true
  }
 ]
}