{
 "title": "PostgreSQL",
 "description": "Performance metrics for Postgres",
 "tags": [
  "postgres",
  "fcio"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(postgresql_checkpoints_req,host)"
   },
   {
    "name": "db",
    "label": "db",
    "query": "label_values(postgresql_tup_fetched{host=\"$host\",db!~\"template.*|postgres\"}, db)"
   }
  ]
 },
 "panels": [
  {
   "title": "Rows",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "fetched",
     "expr": "sum(irate(postgresql_tup_fetched{db=~\"$db\",host=\"$host\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "fetched",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(postgresql_tup_returned{db=~\"$db\",host=\"$host\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "returned",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(postgresql_tup_inserted{db=~\"$db\",host=\"$host\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "inserted",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(postgresql_tup_updated{db=~\"$db\",host=\"$host\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "updated",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetched",
     "expr": "sum(irate(postgresql_tup_deleted{db=~\"$db\",host=\"$host\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "deleted",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(postgresql_xact_commit{host=\"$host\", db=~\"$db\"}[5m]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(rate(postgresql_xact_rollback{host=\"$host\", db=~\"$db\"}[5m]))",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Buffers Allocated",
     "expr": "rate(postgresql_buffers_alloc{host=\"$host\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "alloc",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(postgresql_buffers_backend_fsync{host='$host'}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "backend_fsync",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(postgresql_buffers_backend{host='$host'}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(postgresql_buffers_clean{host='$host'}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "clean",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(postgresql_buffers_checkpoint{host='$host'}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "checkpoint",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(postgresql_numbackends{db=~\"$db\",host=\"$host\"})",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Checkpointing",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "irate(postgresql_checkpoint_sync_time{host=\"$host\"}[5m])",
     "legendFormat": "Sync time"
    },
    {
     "expr": "irate(postgresql_checkpoint_write_time{host=\"$host\"}[5m])",
     "legendFormat": "Write time"
    },
    {
     "expr": "irate(postgresql_checkpoints_timed{host=\"$host\"}[1m]) > 0",
     "legendFormat": "Checkpoint (timed)"
    },
    {
     "expr": "irate(postgresql_checkpoints_req{host=\"$host\"}[1m]) > 0",
     "legendFormat": "Checkpoint (requested)"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "conflicts",
     "expr": "sum(increase(postgresql_deadlocks{db=~\"$db\",host=\"$host\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "deadlocks",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "deadlocks",
     "expr": "sum(increase(postgresql_conflicts{db=~\"$db\",host=\"$host\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "conflicts",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "deadlocks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(postgresql_blks_hit{db=~\"$db\",host=\"$host\"}) / (sum(postgresql_blks_hit{db=~\"$db\",host=\"$host\"}) + sum(postgresql_blks_read{db=~\"$db\",host=\"$host\"}))",
     "legendFormat": "cache hit rate"
    },
    {
     "expr": "sum(irate(postgresql_blks_read{db=~\"$db\",host=\"$host\"}[5m]))",
     "legendFormat": "Blocks read from disk"
    }
   ]
  },
  {
   "title": "Temporary files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(postgresql_temp_bytes{host=\"$host\", db=~\"$db\"}[5m]))",
     "legendFormat": "Bytes written"
    },
    { "metric": "postg" }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "description": "Unclear if this is the right figure.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(diskio_reads{host=\"$host\", name!~\".*[0-9]$\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(diskio_writes{host=\"$host\", name!~\".*[0-9]$\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(cpu_usage_iowait{cpu=\"cpu-total\", host=\"$host\"})",
     "legendFormat": "IOWait"
    },
    {
     "expr": "avg(cpu_usage_system{cpu=\"cpu-total\",host=\"$host\"})",
     "legendFormat": "System"
    },
    {
     "expr": "avg(cpu_usage_user{cpu=\"cpu-total\", host=\"$host\"})",
     "legendFormat": "User"
    },
    {
     "expr": "avg(cpu_usage_idle{cpu=\"cpu-total\",host=\"$host\"})",
     "legendFormat": "Idle"
    },
    {
     "expr": "avg(cpu_usage_steal{cpu=\"cpu-total\",host=\"$host\"})",
     "legendFormat": "Steal"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(mem_used{host=\"$host\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(mem_cached{host=\"$ost\"})",
     "legendFormat": "Cached"
    },
    {
     "expr": "avg(mem_buffered{host=\"$host\"})",
     "legendFormat": "Buffered"
    },
    {
     "expr": "avg(mem_free{host=\"$host\"})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(swap_used{host=\"$host\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(swap_free{host=\"$host\"})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Network ethsrv (Backend)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "avg(rate(net_bytes_recv{host=\"$host\", interface=\"ethsrv\"}[5m])) * 8",
     "legendFormat": "RX "
    },
    {
     "expr": "avg(rate(net_bytes_sent{host=\"$host\", interface=\"ethsrv\"}[5m])) * 8",
     "legendFormat": "TX"
    }
   ]
  }
 ]
}