{
 "title": "Resource Group Overview",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "RG",
    "label": "Resource Group",
    "query": {
     "query": "label_values(system_n_cpus, resource_group)"
    }
   },
   {
    "name": "Host",
    "query": {
     "query": "label_values(system_n_cpus{resource_group=\"$RG\"}, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Host" },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(cpu_usage_iowait{cpu=\"cpu-total\", host=\"$Host\"})",
     "legendFormat": "IOWait"
    },
    {
     "expr": "avg(cpu_usage_system{cpu=\"cpu-total\",host=\"$Host\"})",
     "legendFormat": "System"
    },
    {
     "expr": "avg(cpu_usage_user{cpu=\"cpu-total\", host=\"$Host\"})",
     "legendFormat": "User"
    },
    {
     "expr": "avg(cpu_usage_idle{cpu=\"cpu-total\",host=\"$Host\"})",
     "legendFormat": "Idle"
    },
    {
     "expr": "avg(cpu_usage_steal{cpu=\"cpu-total\",host=\"$Host\"})",
     "legendFormat": "Steal"
    },
    {
     "expr": "avg(system_n_cpus{host=\"$Host\"})",
     "legendFormat": "CPU count"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(mem_used{host=\"$Host\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(mem_cached{host=\"$Host\"})",
     "legendFormat": "Cached"
    },
    {
     "expr": "avg(mem_buffered{host=\"$Host\"})",
     "legendFormat": "Buffered"
    },
    {
     "expr": "avg(mem_free{host=\"$Host\"})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "description": "Unclear if this is the right figure.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(diskio_reads{host=\"$Host\", name!~\".*[0-9]$\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(diskio_writes{host=\"$Host\", name!~\".*[0-9]$\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Network ethsrv (Backend)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg(rate(net_bytes_recv{host=\"$Host\", interface=\"ethsrv\"}[5m])) * 8",
     "legendFormat": "RX "
    },
    {
     "expr": "avg(rate(net_bytes_sent{host=\"$Host\", interface=\"ethsrv\"}[5m])) * 8",
     "legendFormat": "TX"
    }
   ]
  }
 ]
}