{
 "title": "VM Status",
 "tags": [
  "vmstatus",
  "fcio"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": {
     "query": "label_values(system_n_cpus, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Current Values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(system_n_cpus{host=\"$Host\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_n_cpus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(mem_total{host=\"$Host\"})"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(disk_total{host=\"$Host\", path=\"/\"})"
    }
   ]
  },
  {
   "title": "Disk free",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(disk_free{host=\"$Host\", path=\"/\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(system_uptime{host=\"$Host\"})"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(processes_total{host=\"$Host\"})"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(cpu_usage_iowait{cpu=\"cpu-total\", host=\"$Host\"})",
     "legendFormat": "IOWait"
    },
    {
     "expr": "avg(cpu_usage_system{cpu=\"cpu-total\",host=\"$Host\"})",
     "legendFormat": "System"
    },
    {
     "expr": "avg(cpu_usage_user{cpu=\"cpu-total\", host=\"$Host\"})",
     "legendFormat": "User"
    },
    {
     "expr": "avg(cpu_usage_idle{cpu=\"cpu-total\",host=\"$Host\"})",
     "legendFormat": "Idle"
    },
    {
     "expr": "avg(cpu_usage_steal{cpu=\"cpu-total\",host=\"$Host\"})",
     "legendFormat": "Steal"
    }
   ]
  },
  {
   "title": "CPU Pressure (some)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "psi_cpu{period!=\"total\",host=\"$Host\"}",
     "legendFormat": "{{period}}"
    }
   ]
  },
  {
   "title": "Context switches / Forks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(kernel_context_switches{host=\"$Host\"}[5m]))",
     "legendFormat": "Context switches"
    },
    {
     "expr": "avg(rate(kernel_processes_forked{host=\"$Host\"}[5m]))",
     "legendFormat": "Process Forks"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(system_load1{host=\"$Host\"})",
     "legendFormat": "1"
    },
    {
     "expr": "avg(system_load5{host=\"$Host\"})",
     "legendFormat": "5"
    },
    {
     "expr": "avg(system_load15{host=\"$Host\"})",
     "legendFormat": "15"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(processes_total{host=\"$Host\"})",
     "legendFormat": "Processes total"
    },
    {
     "expr": "avg(processes_running{host=\"$Host\"})",
     "legendFormat": "Processes running"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(mem_used{host=\"$Host\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(mem_cached{host=\"$Host\"})",
     "legendFormat": "Cached"
    },
    {
     "expr": "avg(mem_buffered{host=\"$Host\"})",
     "legendFormat": "Buffered"
    },
    {
     "expr": "avg(mem_free{host=\"$Host\"})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(swap_used{host=\"$Host\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(swap_free{host=\"$Host\"})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "psi_memory{period!=\"total\",host=\"$Host\",extent=\"some\"}",
     "legendFormat": "{{period}} some"
    },
    {
     "expr": "-psi_memory{period!=\"total\",host=\"$Host\",extent=\"full\"}",
     "legendFormat": "{{period}} full"
    }
   ]
  },
  { "title": "IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "IOPS",
   "type": "timeseries",
   "description": "Unclear if this is the right figure.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(diskio_reads{host=\"$Host\", name!~\".*[0-9]$\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(diskio_writes{host=\"$Host\", name!~\".*[0-9]$\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "IO Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "psi_io{period!=\"total\",host=\"$Host\",extent=\"some\"}",
     "legendFormat": "{{period}} some"
    },
    {
     "expr": "-psi_io{period!=\"total\",host=\"$Host\",extent=\"full\"}",
     "legendFormat": "{{period}} full"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Disk R/W",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(rate(diskio_read_bytes{host=\"$Host\", name!~\".+[0-9]+\"}[5m])) by (name)",
     "legendFormat": "Read {{name}}"
    },
    {
     "expr": "avg(rate(diskio_write_bytes{host=\"$Host\", name!~\".+[0-9]+\"}[5m])) by (name)",
     "legendFormat": "Write {{name}}"
    }
   ]
  },
  {
   "title": "Disk usage /",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(disk_used{host=\"$Host\", path=\"/\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(disk_free{host=\"$Host\", path=\"/\"})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk usage /tmp",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(disk_used{host=\"$Host\", path=\"/tmp\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(disk_free{host=\"$Host\", path=\"/tmp\"})",
     "legendFormat": "Free"
    }
   ]
  },
  { "title": "Network interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Network ethfe (Frontend)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg(rate(net_bytes_recv{host=\"$Host\", interface=\"ethfe\"}[5m])) * 8",
     "legendFormat": "RX "
    },
    {
     "expr": "avg(rate(net_bytes_sent{host=\"$Host\", interface=\"ethfe\"}[5m])) * 8",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Network ethsrv (Backend)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg(rate(net_bytes_recv{host=\"$Host\", interface=\"ethsrv\"}[5m])) * 8",
     "legendFormat": "RX "
    },
    {
     "expr": "avg(rate(net_bytes_sent{host=\"$Host\", interface=\"ethsrv\"}[5m])) * 8",
     "legendFormat": "TX"
    }
   ]
  },
  { "title": "IP stack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "TCP Connections by State",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(netstat_tcp{host=\"$Host\"}) by (state)",
     "legendFormat": "{{ state }}"
    },
    {}
   ]
  },
  {
   "title": "Connection Tracking Table Data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "conntrack_ip_conntrack_count{host=\"$Host\"}/conntrack_ip_conntrack_max{host=\"$Host\"}",
     "legendFormat": "Conntrack Table Fullness"
    },
    {
     "expr": "conntrack_ip_conntrack_count{host=\"$Host\"}",
     "legendFormat": "Conntrack Table Entries"
    }
   ]
  },
  {
   "title": "UDP Packets / s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(netstat_udp_socket{host=\"$Host\"})",
     "legendFormat": "Sockets"
    },
    {
     "expr": "avg(rate(net_udp_indatagrams{host=\"$Host\"}[5m]))",
     "legendFormat": "IN (legacy)"
    },
    {
     "expr": "avg(rate(net_udp_outdatagrams{host=\"$Host\"}[5m]))",
     "legendFormat": "OUT (legacy)"
    },
    {
     "expr": "avg(rate(net_udp_inerrors{host=\"$Host\"}[5m]))",
     "legendFormat": "IN Errors (legacy)"
    },
    {
     "expr": "avg(rate(nstat_UdpInDatagrams{host=\"$Host\"}[5m]))",
     "legendFormat": "IN (IPv4)"
    },
    {
     "expr": "avg(rate(nstat_Udp6InDatagrams{host=\"$Host\"}[5m]))",
     "legendFormat": "IN (IPv6)"
    },
    {
     "expr": "avg(rate(nstat_UdpOutDatagrams{host=\"$Host\"}[5m]))",
     "legendFormat": "OUT (IPv4)"
    },
    {
     "expr": "avg(rate(nstat_Udp6OutDatagrams{host=\"$Host\"}[5m]))",
     "legendFormat": "OUT (IPv6)"
    },
    {
     "expr": "avg(rate(nstat_UdpInErrors{host=\"$Host\"}[5m]))",
     "legendFormat": "IN Errors (IPv4)"
    },
    {
     "expr": "avg(rate(nstat_Udp6InErrors{host=\"$Host\"}[5m]))",
     "legendFormat": "IN Errors (IPv6)"
    }
   ]
  }
 ]
}