{
 "title": "mysql slow log",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "longest queries",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({job_name=\"mysql/slowlogs\", hostname=\"$host\"} | logfmt --strict | keep query_time, query | unwrap query_time [$__auto]) by (query)",
     "legendFormat": "{{.query}}"
    }
   ]
  },
  {
   "title": "query durations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "avg_over_time({job_name=\"mysql/slowlogs\", hostname=\"$host\"} | logfmt --strict | unwrap query_time [1m]) by (job_name)",
     "legendFormat": "query time"
    },
    {
     "expr": "avg_over_time({job_name=\"mysql/slowlogs\", hostname=\"$host\"} | logfmt --strict | unwrap lock_time [1m]) by (job_name)",
     "legendFormat": "lock time"
    }
   ]
  },
  {
   "title": "rows affected",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time({job_name=\"mysql/slowlogs\", hostname=\"$host\"} | logfmt --strict | unwrap rows_affected [$__auto]) by (job_name)",
     "legendFormat": "query time"
    }
   ]
  },
  {
   "title": "number of queries by user",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "count by(user) (rate({job_name=\"mysql/slowlogs\", hostname=\"$host\"} | logfmt --strict [1m]))",
     "legendFormat": "{{.user}}"
    }
   ]
  },
  {
   "title": "data sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time({job_name=\"mysql/slowlogs\", hostname=\"$host\"} | logfmt --strict | unwrap bytes_sent [$__auto]) by (job_name)",
     "legendFormat": "query time"
    }
   ]
  }
 ]
}